// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Explains the purpose and key elements of Markdown content using a GPT model.
 *
 * - explainMarkdownContent - A function that handles the explanation process.
 * - ExplainMarkdownContentInput - The input type for the explainMarkdownContent function.
 * - ExplainMarkdownContentOutput - The return type for the explainMarkdownContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainMarkdownContentInputSchema = z.object({
  markdownContent: z.string().describe('The Markdown content to be explained.'),
});
export type ExplainMarkdownContentInput = z.infer<
  typeof ExplainMarkdownContentInputSchema
>;

const ExplainMarkdownContentOutputSchema = z.object({
  explanation: z.string().describe('The GPT explanation of the Markdown content.'),
});
export type ExplainMarkdownContentOutput = z.infer<
  typeof ExplainMarkdownContentOutputSchema
>;

export async function explainMarkdownContent(
  input: ExplainMarkdownContentInput
): Promise<ExplainMarkdownContentOutput> {
  return explainMarkdownContentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainMarkdownContentPrompt',
  input: {schema: ExplainMarkdownContentInputSchema},
  output: {schema: ExplainMarkdownContentOutputSchema},
  prompt: `You are an expert in Markdown and web development.

You will analyze the provided Markdown content and provide a clear and concise explanation of its purpose and key elements.

Markdown Content:
{{{markdownContent}}}`,
});

const explainMarkdownContentFlow = ai.defineFlow(
  {
    name: 'explainMarkdownContentFlow',
    inputSchema: ExplainMarkdownContentInputSchema,
    outputSchema: ExplainMarkdownContentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
